version: '3'
services:
  etcdbrowser:
    image: woosley/etcd-browser
    ports:
      - "8080:8080"
    volumes:
      - ./etcd-browser/config.yaml:/app/config.yaml
  etcd:
    image: quay.io/coreos/etcd
    command:
      - /usr/local/bin/etcd
      - "-advertise-client-urls=http://0.0.0.0:2379"
      - "-listen-client-urls=http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    environment:
- ETCD_CORS=*
