version: '3'
services:
  etcdbrowser:
    build: ./etcd-browser/
    ports:
      - "49502:49502"
  etcd:
    image: quay.io/coreos/etcd
    command:
      - /usr/local/bin/etcd
      - "-advertise-client-urls=http://0.0.0.0:49501"
      - "-listen-client-urls=http://0.0.0.0:49501"
    ports:
      - "49501:49501"
    environment:
      - ETCD_CORS=*
