---
swagger: "2.0"
info:
  description: "This is a simple API description for the ScaleIT app registry\n* Check\
    \ the [etcd](https://coreos.com/etcd/docs/latest/v2/api.html) api description\
    \ for further information\n"
  version: "1.0.0"
  title: "ScaleIT-ORG ETCD Store"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "kuhn@teco.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/ScaleIT-ORG/ETCD/1.0.0"
tags:
- name: "App Registration"
  description: "App Management"
schemes:
- "https"
- "http"
paths:
  /v2/keys/:
    get:
      tags:
      - "App Registration"
      parameters:
      - name: "recursive"
        in: "query"
        description: "Specifies if all the sub-keys/properties should be contained\
          \ in the response"
        required: false
        type: "boolean"
      responses:
        200:
          description: "Returns all applications with all its properties. ?recursive=true\
            \ needed if you want to get all values"
    delete:
      tags:
      - "App Registration"
      summary: "Delete a all Apps"
      parameters:
      - name: "recursive"
        in: "query"
        description: "Specifies if all the sub-keys/properties should be deleted"
        required: false
        type: "boolean"
      responses:
        200:
          description: "Successfull operation"
  /v2/keys/{AppID}/:
    get:
      tags:
      - "App Registration"
      parameters:
      - name: "AppID"
        in: "path"
        description: "ID of App to return"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "Returns the application with all its properties"
          schema:
            $ref: "#/definitions/App"
    put:
      tags:
      - "App Registration"
      parameters: []
      responses:
        200:
          description: "successful operation"
    delete:
      tags:
      - "App Registration"
      summary: "Delete a specific Apps"
      parameters: []
      responses:
        200:
          description: "Successfull operation"
  /v2/keys/{AppID}/{property}:
    get:
      tags:
      - "App Registration"
      parameters:
      - name: "AppID"
        in: "path"
        description: "ID of App to return"
        required: true
        type: "string"
        format: "string"
      - name: "property"
        in: "path"
        description: "property of App to set"
        required: true
        type: "string"
        format: "string"
      responses:
        200:
          description: "Returns requested property value"
    put:
      tags:
      - "App Registration"
      parameters: []
      responses:
        200:
          description: "successful operation"
    delete:
      tags:
      - "App Registration"
      summary: "Delete a property"
      parameters: []
      responses:
        200:
          description: "Successfull operation"
  /health:
    get:
      tags:
      - "App Registration"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/HealthStatus"
definitions:
  HealthStatus:
    type: "object"
    required:
    - "health"
    properties:
      health:
        type: "string"
        example: "true"
    example:
      health: "true"
  App:
    type: "object"
    required:
    - "url"
    properties:
      url:
        type: "string"
        example: "staging.teco.edu"
      App_Icon:
        type: "string"
        example: "/img/fav.ico"
      AppHub_Icon:
        type: "string"
        example: "/img/appHub.ico"
      appType:
        type: "string"
        example: "platform-essentials-app-registry"
      lifecycleStatus:
        type: "string"
        example: "Online"
      description:
        type: "string"
        example: "My Description 123"
      visibleForRole:
        type: "string"
        example: "TODO"
    example:
      lifecycleStatus: "Online"
      App_Icon: "/img/fav.ico"
      appType: "platform-essentials-app-registry"
      description: "My Description 123"
      visibleForRole: "TODO"
      AppHub_Icon: "/img/appHub.ico"
      url: "staging.teco.edu"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
